site:
  title: Apache
  url: https://felix.apache.org
content:
  sources:
  - url: https://github.com/apache/felix-antora-site.git
    branches: main
#  - url: ./../felix-dev
#    branches: HEAD
#    start_paths:
#      - scr

asciidoc:
  attributes:
    allow-uri-read: true
  extensions:
    - asciidoctor-kroki
    - "@djencks/asciidoctor-antora-indexer"
    - "@djencks/asciidoctor-jsonpath"

ui:
  bundle:
    url: node_modules/@felix/felix-antora-ui/build/felix-antora-ui-bundle.zip
    snapshot: false
  #currently .htaccess has to be copied by hand, see https://gitlab.com/antora/antora/-/issues/627 and package.json
  supplemental_files: ./supplemental-ui

#output:
#  clean: true
