site:
  title: Apache
  url: https://felix.apache.org
content:
  sources:
  - url: ./../felix-site

asciidoc:
  attributes:
    allow-uri-read: true
  extensions:
    - asciidoctor-kroki
    - "@djencks/asciidoctor-antora-indexer"

ui:
  bundle:
    url: node_modules/@felix/felix-antora-ui/build/felix-antora-ui-bundle.zip
    snapshot: false

output:
  clean: true
