site:
  title: Apache Felix
  url: https://felix.apache.org
  start_page: documentation::index.adoc

content:
  sources:
    #  For local "author mode" builds check out this felix-antora playbook project
    #  and the site project next to one another and uncomment the next two lines and comment out the other - url
#    - url: ./../felix-antora-site
#      branches: HEAD
    # For "production" build without needing a local site checkout uncomment the next two lines and comment out the previous two.
  - url: https://github.com/apache/felix-antora-site.git
    branches: main
#  - url: ./../felix-dev
#    branches: HEAD
#    start_paths:
#      - scr

asciidoc:
  attributes:
    allow-uri-read: true
  extensions:
    - asciidoctor-kroki
    - "@djencks/asciidoctor-antora-indexer"
    - "@djencks/asciidoctor-jsonpath"

ui:
  bundle:
    url: "./node_modules/@apache-felix/felix-antora-ui/build/felix-antora-ui-bundle.zip"
    snapshot: false
  #currently .htaccess has to be copied by hand, see https://gitlab.com/antora/antora/-/issues/627 and package.json
  supplemental_files: ./supplemental-ui

urls:
  redirect_facility: httpd

#output:
#  clean: true
